# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build
        run: cl /EHsc src/main.cpp src/Postfix.cpp /link /out:task.exe
        
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: task.exe
          retention-days: 1
          
  telegram_message: 
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      
#       - name: Download artifact
#         uses: aochmann/actions-download-artifact@1.0.0
#         with:
#           name: my-artifact
      - name: Download artifact from build
        uses: bettermarks/action-artifact-download@0.1.0
        with:
          artifact_name: my-artifact
                
      - name: test
        run: ls

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_DEBUG }}
          token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
          message: Alexey Klimov
          document: task.exe
